meta_product_name: "Chante, chante, chante"
meta_title: "Chante, chante, chante - Aprende o francês con músicas"
meta_description: "Chante, chante, chante vai te sugerir músicas francesas para melhorar o seu francês"
meta_image: "meta.png" # should exist in `app/assets/images/`

